server:
  port: ${port:6001}

spring:
  application:
    name: admin-server
  cloud:
    config:
      discovery:
        enabled: false
  security:
    user:
      name: "username"
      password: "password"
  boot:
    admin:
      client:
        instance:
          metadata:
            user.name: "username"
            user.password: "password"