server:
  port: 8080

spring:
  application:
    name: proxy-server
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1

management:
  endpoints:
    health:
      enabled: true

ribbon:
  serverListRefreshInterval: 1000
  ConnectTimeout: 6000
  ReadTimeout: 3000
  SocketTimeout: 6000

zuul:
  ignoredServices: '*'
  routes:
    biz1-application:
      path: /biz1/**
      serviceId: biz1-application
      stripPrefix: true
    biz2-application:
      path: /biz2/**
      serviceId: biz2-application
      stripPrefix: true
