spring:
  boot:
    admin:
      client:
        url: http://localhost:6001
        username: username
        password: password

ribbon:
  serverListRefreshInterval: 1000
  ConnectTimeout: 6000
  ReadTimeout: 3000

hystrix.commanddefault.execution.isolation.thread.timeoutInMilliseconds: 10000

feign.hystrix.enabled: true

management.endpoints.web.exposure.include: "*"